---
app:
  persistence:
    datasource:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: admin123
      url: jdbc:postgresql://127.0.0.1:5432/app?ssl=false
    jpa:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      generate-ddl: false
      show-sql: false
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false

  kafka:
    input-topic-name: input-data
    general-topic-name: general-data
    create-topics: false

# Spring configuration
spring:
  kafka:
    bootstrap-servers:
      - localhost:29092
    consumer:
      bootstrap-servers:
        - localhost:29092
      group-id: input-processor

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}
